neuron_app/blueprints/pages/routes.py
#blueprints/pages/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from neuron_app import db
from ...models import Page
from ...forms import PageForm

pages_bp = Blueprint('pages', __name__)

@pages_bp.route('/p/<page_name>')
def show_page(page_name):
    page = Page.query.filter_by(title=page_name).first()
    pages = Page.query.all()  # Query to get all pages

    return render_template('/pages/page.html', page=page, pages=pages)

@pages_bp.route('/add_page', methods=['GET', 'POST'])
def add_page():
    pages = Page.query.all()  # Query to get all pages

    form = PageForm()
    if form.validate_on_submit():
        is_header = form.is_header.data  # Check if the page should be marked as a header
        page = Page(title=form.title.data, content=form.content.data, is_header=is_header)
        db.session.add(page)
        db.session.commit()
        return redirect(url_for('pages.show_page', page_name=page.title))
    return render_template('/pages/_addpage.html', form=form, pages=pages)



@pages_bp.route('/edit_page/<page_title>', methods=['GET', 'POST'])
def edit_page(page_title):
    pages = Page.query.all()  # Query to get all pages

    page = Page.query.filter_by(title=page_title).first_or_404()
    form = PageForm(obj=page)

    if form.validate_on_submit():
        page.title = form.title.data
        page.content = form.content.data
        
        # Dodajte sledeći blok koda da označite stranicu kao zaglavlje (header)
        is_header = form.is_header.data
        page.is_header = is_header

        db.session.commit()
        flash('Page updated successfully!', 'success')
        return redirect(url_for('pages.show_page', page_name=page.title))

    return render_template('/pages/_editpage.html', form=form, page=page, pages=pages)



@pages_bp.route('/delete_page/<page_title>', methods=['POST', 'GET'])
def delete_page(page_title):
    
    page = Page.query.filter_by(title=page_title).first_or_404()
    db.session.delete(page)
    db.session.commit()
    flash('Page deleted successfully!', 'success')
    return redirect(url_for('admin.dashboard'))

neuron_app/templates/pages/_addpage.html
{% extends 'base.html' %} {% block content %}
<h2>Add Page</h2>
<form method="post" action="{{ url_for('pages.add_page') }}">
  {{ form.hidden_tag() }}
  <div class="mb-3">
    {{ form.title.label }} {{ form.title(class="form-control") }}
  </div>

  <div class="mb-3">
    {{ form.content.label(class="form-label") }}
    <textarea
      name="content"
      class="form-control tinymce_"
      placeholder="Enter content"
    >
{{ form.content.data }}</textarea
    >
    {% if form.content.errors %}
    <div class="invalid-feedback">
      {% for error in form.content.errors %} {{ error }} {% endfor %}
    </div>
    {% endif %}
  </div>

  <!-- Checkbox for Make it Header -->
  <div class="mb-3 form-check">
    {{ form.is_header(class="form-check-input") }} {{
    form.is_header.label(class="form-check-label") }}
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

neuron_app/templates/pages/_editpage.html
{% extends 'base.html' %} {% block content %}
<div class="container mt-4">
  <h2 class="mb-3">Edit Page</h2>
  <form
    action="{{ url_for('pages.edit_page', page_title=page.title) }}"
    method="POST"
  >
    {{ form.hidden_tag() }}

    <div class="mb-3">
      <label for="title" class="form-label">Title</label>
      {{ form.title(class="form-control") }} {% if form.title.errors %}
      <div class="alert alert-danger">
        {% for error in form.title.errors %}
        <p>{{ error }}</p>
        {% endfor %}
      </div>
      {% endif %}
    </div>

    <div class="mb-3">
      {{ form.content.label(class="form-label") }} {% if form.content.errors %}
      <div class="invalid-feedback">
        {% for error in form.content.errors %} {{ error }} {% endfor %}
      </div>
      {% endif %}
      <!-- Dodajte TinyMCE editor za unos sadržaja -->
      <textarea
        class="form-control tinymce_"
        id="content"
        name="content"
        placeholder="Enter content"
        rows="10"
      >
        {{ form.content.data | safe }}
      </textarea>
    </div>

    <div class="mb-3 form-check">
      {{ form.is_header(class="form-check-input") }}
      <label class="form-check-label" for="is_header">Make it Header</label>
    </div>

    <button type="submit" class="btn btn-primary">Update Page</button>
  </form>
</div>
{% endblock %}

neuron_app/templates/pages/page.html
{% extends 'base.html' %} {% block content %}
<div class="container mt-4">
  {% if current_user.is_authenticated and current_user.is_admin %}
  <a
    href="{{ url_for('pages.edit_page', page_title=page.title) }}"
    class="btn btn-info mb-3"
    >Edit Page</a
  >
  <a href="{{ url_for('pages.add_page') }}" class="btn btn-warning mb-3"
    >Add Pages</a
  >
  <br />
  <br />
  {% endif %}
  <h1 class="display-4 text-center">{{ page.title }}</h1>
  <hr class="my-4" />
  <div class="tinymce-content">
    <p class="text-justify">{{ page.content | safe }}</p>
  </div>
  <!-- Dodatni detalji o stranici... -->
</div>
{% endblock %}