neuron_app/blueprints/main.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from neuron_app import db # Import from main directory
from ..models import News, Page
from ..forms import NewsForm, CommentForm 
import requests
from bs4 import BeautifulSoup
from flask_login import current_user




main_bp = Blueprint('main', __name__)


@main_bp.route('/home/load')
def load_news():
    news_items = News.query.all()
    return render_template('news_list.html', news_items=news_items)

@main_bp.route('/')
@main_bp.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    news_items = News.query.order_by(News.created_at.desc()).paginate(page=page, per_page=2)
    pages = Page.query.all()  # Query to get all pages
    forms = {news_item.id: CommentForm() for news_item in news_items.items}
    return render_template('home.html', news_items=news_items, pages=pages, forms=forms)



def get_latest_videos(channel_url):
    response = requests.get(channel_url)
    soup = BeautifulSoup(response.text, 'html.parser')

    videos = []
    for video in soup.find_all('a', id='thumbnail'):
        video_link = video.get('href')
        if video_link and '/watch?v=' in video_link:
            video_id = video_link.split('/watch?v=')[1].split('&')[0]  # Izdvajanje video ID-a
            title = video.get('title')
            if title:
                videos.append({
                    'title': title,
                    'video_id': video_id
                })
    return videos


@main_bp.route('/videos')
def show_videos():
    channel_url = 'https://www.youtube.com/channel/UC1kGH2CKT0s2Xn2HlkT7HtQ/videos'  # Ispravite URL

    videos = get_latest_videos(channel_url)
    return render_template('videos.html', videos=videos)

neuron_app/blueprints/news/routes.py
import os
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, jsonify
from werkzeug.utils import secure_filename
from neuron_app import db
from ...models import News, Page, Comment
from ...forms import NewsForm, CommentForm
from slugify import slugify
from neuron_app import uploaded_images
from itertools import groupby
from flask_login import current_user

news_bp = Blueprint('news', __name__)


#URL /news/
@news_bp.route('/news/')
def show_news():
    pages = Page.query.all()
    page = request.args.get('page', 1, type=int)
    news_items = News.query.order_by(News.created_at.desc()).paginate(page=page, per_page=25)

    # Grupisanje novosti po mesecu i godini
    grouped_news = {}
    for item in news_items.items:
        if item.created_at:
            year_month = item.created_at.strftime('%Y-%m')
            if year_month not in grouped_news:
                grouped_news[year_month] = []
            grouped_news[year_month].append(item)

    return render_template('/news/news.html', grouped_news=grouped_news, news_items=news_items, pages=pages)



#URL /news/add_news/
@news_bp.route('/add_news', methods=['GET', 'POST'])
def add_news():
    pages = Page.query.all()
    form = NewsForm()
    if form.validate_on_submit():
        news = News(title=form.title.data, content=form.content.data)
        news.slug = slugify(form.title.data)
        if form.image.data:
            filename = secure_filename(form.image.data.filename)
            image_path = os.path.join(current_app.root_path, 'static/images', filename)
            form.image.data.save(image_path)
            news.featured_image = filename
        db.session.add(news)
        db.session.commit()
        flash('News added successfully!')
        return redirect(url_for('main.home'))
    return render_template('/news/_addnews.html', form=form, pages=pages)


@news_bp.route('/n/<string:news_slug>')
def news_detail(news_slug):
    pages = Page.query.all()
    news_item = News.query.filter_by(slug=news_slug).first_or_404()
    
    # Inkrementiranje broja klikova
    news_item.click_count = news_item.click_count + 1 if news_item.click_count else 1
    db.session.commit()
    
    return render_template('/news/single_news.html', news_item=news_item, pages=pages)



@news_bp.route('/edit_news/<string:news_slug>', methods=['GET', 'POST'])
def edit_news(news_slug):
    news = News.query.filter_by(slug=news_slug).first_or_404()
    form = NewsForm(obj=news)
    pages = Page.query.all()
    if form.validate_on_submit():
        news.title = form.title.data
        news.content = form.content.data

        # Ažuriranje slike
        if form.image.data:
            if news.featured_image:
                os.remove(os.path.join(current_app.root_path, 'static/images', news.featured_image))
            
            filename = secure_filename(form.image.data.filename)
            form.image.data.save(os.path.join(current_app.root_path, 'static/images', filename))
            news.featured_image = filename

        db.session.commit()
        flash('News Updated Successfully!', 'success')
        # Preusmeravanje ili renderovanje stranice
        return redirect(url_for('news.news_detail', news_slug=news_slug))

    return render_template('/news/_editnews.html', form=form, news=news, pages=pages)



#URL /news/delete_news/<int:news_id>
@news_bp.route('/delete_news/<int:news_id>', methods=['POST'])
def delete_news(news_id):
    news = News.query.get_or_404(news_id)
    Comment.query.filter_by(news_id=news.id).delete()
    db.session.delete(news)
    db.session.commit()
    flash('News Deleted Successfully!', 'success')
    return redirect(url_for('main.home'))


@news_bp.route('/increment_click/<int:news_id>', methods=['POST'])
def increment_click(news_id):
    news_item = News.query.get_or_404(news_id)
    news_item.click_count += 1
    db.session.commit()
    return jsonify({'click_count': news_item.click_count})





#KOMENTARI
@news_bp.route('/add_comment/<int:news_id>', methods=['POST'])
def add_comment(news_id):
    form = CommentForm()
    news_item = News.query.get_or_404(news_id)
    if form.validate_on_submit():
        comment = Comment(content=form.content.data, news_id=news_id, user_id=current_user.id)
        db.session.add(comment)
        db.session.commit()

        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return jsonify({
                'status': 'success',
                'message': 'Komentar je uspešno dodat.',
                'comment_html': render_template('_comment.html', comment=comment)
            })
        else:
            flash('Komentar je uspešno dodat.')
            return redirect(url_for('main.home'))  # Ili neka druga odgovarajuća ruta

    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return jsonify({'status': 'error', 'message': 'Greška u formi.'})
    return render_template('_addcomment.html', form=form, news_item=news_item)




@news_bp.route('/delete_comment/<int:comment_id>', methods=['POST'])
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user.id != comment.author.id and not current_user.is_admin:
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return jsonify({'status': 'error', 'message': 'Nemate dozvolu za brisanje ovog komentara.'})
        else:
            flash('Nemate dozvolu za brisanje ovog komentara.')
            return redirect(url_for('main.home'))
    
    db.session.delete(comment)
    db.session.commit()

    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return jsonify({'status': 'success', 'message': 'Komentar je uspešno obrisan.'})
    else:
        flash('Komentar je uspešno obrisan.')
        return redirect(url_for('main.home'))  # Preusmerite na odgovarajuću stranicu

neuron_app/blueprints/pages/routes.py
#blueprints/pages/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from neuron_app import db
from ...models import Page
from ...forms import PageForm

pages_bp = Blueprint('pages', __name__)

@pages_bp.route('/p/<page_name>')
def show_page(page_name):
    page = Page.query.filter_by(title=page_name).first()
    pages = Page.query.all()  # Query to get all pages

    return render_template('/pages/page.html', page=page, pages=pages)

@pages_bp.route('/add_page', methods=['GET', 'POST'])
def add_page():
    pages = Page.query.all()  # Query to get all pages

    form = PageForm()
    if form.validate_on_submit():
        is_header = form.is_header.data  # Check if the page should be marked as a header
        page = Page(title=form.title.data, content=form.content.data, is_header=is_header)
        db.session.add(page)
        db.session.commit()
        return redirect(url_for('pages.show_page', page_name=page.title))
    return render_template('/pages/_addpage.html', form=form, pages=pages)



@pages_bp.route('/edit_page/<page_title>', methods=['GET', 'POST'])
def edit_page(page_title):
    pages = Page.query.all()  # Query to get all pages

    page = Page.query.filter_by(title=page_title).first_or_404()
    form = PageForm(obj=page)

    if form.validate_on_submit():
        page.title = form.title.data
        page.content = form.content.data
        
        # Dodajte sledeći blok koda da označite stranicu kao zaglavlje (header)
        is_header = form.is_header.data
        page.is_header = is_header

        db.session.commit()
        flash('Page updated successfully!', 'success')
        return redirect(url_for('pages.show_page', page_name=page.title))

    return render_template('/pages/_editpage.html', form=form, page=page, pages=pages)



@pages_bp.route('/delete_page/<page_title>', methods=['POST', 'GET'])
def delete_page(page_title):
    
    page = Page.query.filter_by(title=page_title).first_or_404()
    db.session.delete(page)
    db.session.commit()
    flash('Page deleted successfully!', 'success')
    return redirect(url_for('admin.dashboard'))

neuron_app/templates/_addcomment.html
<!-- _addcomment.html -->
<div
  id="comments_{{ news_item.id }}"
  class="comments-section"
  style="display: none"
>
  <!-- Prikazani komentari -->
  <div class="comment-list">
    {% for comment in news_item.comments %}
    <div class="comment">
      <div class="row">
        <div class="col">
          <h6>
            <strong class="text-success">{{ comment.author.username }}</strong>
            <small class="text-muted ms-2"
              >{{ moment(comment.created_at).fromNow() }}</small
            >
          </h6>
          <p>{{ comment.content }}</p>
        </div>
        <div class="col-auto">
          {% if current_user.is_authenticated and (current_user.id ==
          comment.author.id or current_user.is_admin) %}
          <form
            action="{{ url_for('news.delete_comment', comment_id=comment.id) }}"
            method="post"
            class="delete-comment-form"
          >
            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
          </form>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <!-- Show more button -->
  <!----  <div class="text-center"> -->
  <!--  <button class="btn btn-dark show-more-comments">more</button> -->
  <!-- </div> -->

  <!-- Comment Box -->
  {% if current_user.is_authenticated %}
  <div class="card mt-4">
    <div class="card-body">
      <form
        method="POST"
        action="{{ url_for('news.add_comment', news_id=news_item.id) }}"
        class="comment-form"
      >
        {{ forms[news_item.id].hidden_tag() }}
        <div class="mb-3">
          {{ forms[news_item.id].content.label(class="form-label text-white") }}
          {{ forms[news_item.id].content(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
  {% endif %}
</div>

neuron_app/templates/_comment.html
<div class="card mb-3 comment" id="comment_{{ comment.id }}">
  <div class="card-body">
    <div class="row">
      <div class="col">
        <h6 class="card-title">
          <strong>{{ comment.author.username }}</strong>
          <small class="text-muted ms-2"
            >{{ moment(comment.created_at).fromNow() }}</small
          >
        </h6>
        <p class="card-text">{{ comment.content }}</p>
      </div>

      <!-- Dugme za brisanje (vidljivo samo autoru komentara ili adminu) -->
      <div class="col-auto">
        {% if current_user.is_authenticated and (current_user.id ==
        comment.author.id or current_user.is_admin) %}
        <form
          action="{{ url_for('news.delete_comment', comment_id=comment.id) }}"
          method="post"
          class="delete-comment-form"
        >
          <button type="submit" class="btn btn-danger btn-sm">Delete</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>

neuron_app/templates/_edituser.html
{% extends 'base.html' %} {% block content %}
<div class="container mt-4">
  <h2>Edit User</h2>
  <form action="" method="post">
    {{ form.hidden_tag() }}
    <div class="form-group">
      <label for="username">Username</label>
      {{ form.username(class="form-control") }} {% for error in
      form.username.errors %}
      <span style="color: red">[{{ error }}]</span>
      {% endfor %}
    </div>
    <div class="form-group">
      <label for="email">Email</label>
      {{ form.email(class="form-control") }} {% for error in form.email.errors
      %}
      <span style="color: red">[{{ error }}]</span>
      {% endfor %}
    </div>
    <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="is_admin"
      name="is_admin" {{ 'checked' if form.is_admin.data else '' }}>
      <label class="form-check-label" for="is_admin">Admin</label>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
  </form>
</div>
{% endblock %}

neuron_app/templates/dyn_nav_links.html
<!-- About the Trainer -->
<li class="nav-item dropdown">
  <a
    class="nav-link dropdown-toggle"
    href="#"
    id="aboutDropdown"
    role="button"
    data-bs-toggle="dropdown"
    aria-expanded="false"
    >Discover</a
  >
  <ul class="dropdown-menu" aria-labelledby="aboutDropdown">
    <!-- Dynamically Added Pages -->
    {% set current_category = None %} {% for page in pages %} {% if
    page.is_header %} {% if current_category %} {% endif %}
    <li>
      <h5 class="dropdown-item disabled">{{ page.title }}</h5>
    </li>
    {% set current_category = page.title %} {% else %}
    <li>
      <a
        class="dropdown-item"
        href="{{ url_for('pages.show_page', page_name=page.title) }}"
        >{{ page.title }}</a
      >
    </li>
    {% endif %} {% endfor %}
    <!-- ...rest of your static items... -->
  </ul>
</li>

neuron_app/templates/error.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1>404</h1>
  <p>Page not found.</p>
</div>
{% endblock %}

neuron_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<div class="container mt-4">
  <!-- Admin Controls -->
  {% if current_user.is_authenticated and current_user.is_admin %}
  <a href="{{ url_for('news.add_news') }}" class="btn btn-success mb-3"
    >Add News</a
  >
  <a href="{{ url_for('pages.add_page') }}" class="btn btn-warning mb-3"
    >Add Pages</a
  >
  {% endif %}

  <!-- News Items Loop -->
  {% for news_item in news_items %}
  <div class="row mb-4">
    <div class="col">
      <div class="card">
        {% if news_item.featured_image %}
        <img
          src="{{ url_for('static', filename='images/' + news_item.featured_image) }}"
          alt="{{ news_item.title }}"
          class="card-img-top"
          style="max-height: 250px; object-fit: cover"
        />
        {% endif %}
        <div class="card-body">
          <h2 class="card-title">
            <a
              href="{{ url_for('news.news_detail', news_slug=news_item.slug) }}"
              >{{ news_item.title }}</a
            >
          </h2>
          <div class="d-flex justify-content-between align-items-center mb-2">
            <div>
              <small
                ><i class="bi bi-calendar" style="font-size: 1.2rem"></i>
                Published: {{ moment(news_item.created_at).fromNow(refresh=True)
                }}</small
              ><br />
              {% set read_time = calculate_read_time(news_item.content) %}
              <small
                ><i
                  class="bi bi-clock {{ 'color-red' if read_time <= 2 else 'color-orange' if read_time <= 4 else 'color-yellow' if read_time <= 6 else 'color-lightgreen' if read_time <= 8 else 'color-green' }}"
                  style="font-size: 1.2rem"
                ></i>
                {{ read_time }} min read time</small
              >
            </div>
            {% if current_user.is_authenticated and current_user.is_admin %}
            <div>
              <a
                href="{{ url_for('news.edit_news', news_slug=news_item.slug) }}"
                class="btn btn-sm btn-secondary"
                >Edit</a
              >
              <form
                action="{{ url_for('news.delete_news', news_id=news_item.id) }}"
                method="post"
                class="d-inline"
              >
                <button type="submit" class="btn btn-sm btn-danger">
                  Delete
                </button>
              </form>
            </div>
            {% endif %}
          </div>
          <hr />
          <div
            id="tinymce_{{ news_item.id }}"
            style="max-width: 100%; overflow: hidden"
          >
            {{ news_item.content[:760] | safe | striptags | escape }}
          </div>
          <div class="text-end">
            <div id="viewCounter_{{ news_item.id }}">
              Views:
              <span
                class="numberOfViews"
                data-views="{{ news_item.click_count }}"
                >0</span
              ><span class="tooltip">View info</span>
            </div>
            <div id="commentCounter_{{ news_item.id }}">
              Comments:
              <span class="numberOfComments"
                >{{ news_item.comments.count() }}</span
              >
            </div>
          </div>
        </div>
        <button
          class="btn btn-dark"
          type="button"
          onclick="toggleComments('comments_{{ news_item.id }}')"
        >
          Comments
        </button>
        {% include '_addcomment.html' %}
      </div>
    </div>
  </div>
  {% endfor %}

  <!-- Pagination -->
  <div class="text-center mb-3">
    {% if news_items.has_prev %}<a
      href="{{ url_for('main.home', page=news_items.prev_num) }}"
      class="btn btn-primary"
      >Previous</a
    >{% endif %} {% if news_items.has_next %}<a
      href="{{ url_for('main.home', page=news_items.next_num) }}"
      class="btn btn-primary"
      >Next</a
    >{% endif %}
    <div><span>Page {{ news_items.page }} of {{ news_items.pages }}</span></div>
  </div>
</div>

<!-- JavaScript -->
<script>
  // JavaScript
  document.addEventListener("DOMContentLoaded", function () {
    const commentsList = document.querySelector(".comment-list");
    const comments = Array.from(commentsList.querySelectorAll(".comment"));

    // Sakrijemo sve komentare
    comments.forEach((comment) => {
      comment.style.display = "none";
    });

    // Prikazujemo prvih 4 komentara (ako ih ima)
    for (let i = 0; i < 4 && i < comments.length; i++) {
      comments[i].style.display = "block";
    }

    // Prikazi "Show more" dugme samo ako ima više od 4 komentara
    if (comments.length > 4) {
      const showMoreButton = document.createElement("button");
      showMoreButton.className = "btn btn-dark show-more-comments";
      showMoreButton.type = "button";
      showMoreButton.textContent = "Show more";
      commentsList.appendChild(showMoreButton);

      showMoreButton.addEventListener("click", function () {
        for (let i = 4; i < comments.length; i++) {
          comments[i].style.display = "block";
        }
        // Sakrijemo "Show more" dugme nakon prikazivanja svih komentara
        this.style.display = "none";
      });
    }
  });

  // View Counter Style Update
  document.addEventListener("DOMContentLoaded", function () {
    document.querySelectorAll(".numberOfViews").forEach(function (element) {
      var numberOfViews = parseInt(element.getAttribute("data-views"));
      element.textContent = numberOfViews;

      // Dodajte ovu liniju za postavljanje klase prema nivou toplote
      element.classList.add(getHeatLevelClass(numberOfViews));
    });
  });

  // Funkcija za određivanje klase prema nivou toplote
  function getHeatLevelClass(views) {
    if (views < 100) {
      return "hot-low";
    } else if (views < 200) {
      return "hot-medium";
    } else if (views < 400) {
      return "hot-preheat";
    } else if (views < 500) {
      return "hot-heating";
    } else if (views < 1000) {
      return "hot-fire";
    } else {
      return "hot-high";
    }
  }

  function updateViewStyle(views, element) {
    // Style logic based on views count
  }

  // Toggle Comments Section
  function toggleComments(commentsId) {
    var commentsSection = document.getElementById(commentsId);
    commentsSection.style.display =
      commentsSection.style.display === "none" ? "block" : "none";
  }

  // AJAX za Dodavanje Komentara
  document.querySelectorAll(".comment-form").forEach((form) => {
    form.addEventListener("submit", function (event) {
      event.preventDefault();
      var formData = new FormData(this);

      fetch(this.action, {
        method: "POST",
        body: formData,
        headers: {
          "X-Requested-With": "XMLHttpRequest",
        },
      })
        .then((response) => response.json())
        .then((data) => {
          if (data.status === "success") {
            // Create a new comment element
            var newComment = document.createElement("div");
            newComment.className = "comment";
            newComment.innerHTML = data.comment_html;

            // Append the new comment to the comments list
            var commentsList =
              this.closest(".comments-section").querySelector(".comment-list");
            commentsList.appendChild(newComment);

            // Reset the form
            this.reset();
          } else {
            alert(data.message);
          }
        })
        .catch((error) => {
          alert("Error adding comment.");
        });
    });
  });

  // Handler za brisanje komentara
  function deleteCommentHandler(event) {
    event.preventDefault();
    var formData = new FormData(this);
    console.log("Brisanje komentara funkcija je pozvana"); // Dodajte ovu liniju

    fetch(this.action, {
      method: "POST",
      body: formData,
      headers: {
        "X-Requested-With": "XMLHttpRequest",
      },
    })
      .then((response) => response.json())
      .then((data) => {
        if (data.status === "success") {
          var commentId = this.closest(".comment").id;
          document.getElementById(commentId).remove();
        } else {
          alert(data.message);
        }
      })
      .catch((error) => {
        alert("Error deleting comment.");
      });
  }

  // AJAX za Dodavanje Komentara
  // ...

  // Nakon uspešnog dodavanja novog komentara...
  // ...

  // refreshDeleteCommentForms(); // Pozvati ovu funkciju da osvežite event listener-e za brisanje komentara
</script>

{% endblock %}

neuron_app/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
  <div class="container">
    <a class="navbar-brand" href="{{ url_for('main.home') }}">S.DRAGIC</a>
    <div class="d-flex">
      <!-- Dugme za prebacivanje tema pored hamburger menija -->
      <button
        class="btn btn-link nav-link d-lg-none"
        type="button"
        id="themeToggle"
      >
        <i class="bi bi-sun-fill" id="theme-icon"></i>
      </button>
      <!-- Hamburger meni dugme -->
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('news.show_news') }}">News</a>
        </li>
        <li>{% include 'nav_links.html' %}</li>
        <li>{% include 'dyn_nav_links.html' %}</li>
        <!-- Dodatni linkovi ako su potrebni -->
      </ul>

      <ul class="navbar-nav">
        <!-- Prebacivanje teme vidljivo samo na velikim ekranima -->
        <li class="nav-item d-none d-lg-block">
          <button
            aria-expanded="false"
            class="btn btn-link nav-link py-2 px-0 px-lg-3"
            type="button"
            id="themeToggleDesktop"
          >
            <i class="bi bi-sun-fill" id="theme-icon-desktop"></i>
          </button>
        </li>
      </ul>

      <!-- Profil Dropdown -->
      {% if current_user.is_authenticated %}
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{ current_user.username | upper }}
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdown"
          >
            <li>
              <h6 class="dropdown-header">Personal Settings</h6>
            </li>
            <li>
              <a class="dropdown-item" href="#">Profile</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Settings</a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <h6 class="dropdown-header text-primary-emphasis">
                Membership <i class="bi bi-patch-check-fill text-primary"></i>
              </h6>
            </li>
            <li>
              <a class="dropdown-item" href="#">Messages</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Calendar</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Sessions</a>
            </li>
            {% if current_user.is_admin %}
            <!-- Ovo će biti prikazano samo administratorima -->
            <li><hr class="dropdown-divider" /></li>
            <li><h6 class="dropdown-header">Administration</h6></li>
            <li>
              <a class="dropdown-item" href="{{ url_for('admin.dashboard') }}"
                >Settings</a
              >
            </li>
            <li>
              <a
                class="dropdown-item text-success-emphasis"
                href="{{ url_for('news.add_news') }}"
                >News</a
              >
            </li>
            <li>
              <a
                class="dropdown-item text-warning-emphasis"
                href="{{ url_for('pages.add_page') }}"
                >Pages</a
              >
            </li>
            <!-- Kraj administrator sekcije -->
            {% endif %}
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="{{ url_for('auth.logout') }}"
                >Logout</a
              >
            </li>
          </ul>
        </li>
      </ul>
      {% else %}
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

<script>
  function toggleThemeAndIcon(themeIconId) {
    const themeIcon = document.getElementById(themeIconId);
    const currentTheme =
      document.documentElement.getAttribute("data-bs-theme") === "dark"
        ? "light"
        : "dark";
    document.documentElement.setAttribute("data-bs-theme", currentTheme);
    sessionStorage.setItem("preferredTheme", currentTheme);

    if (currentTheme === "light") {
      themeIcon.className = "bi bi-moon-fill"; // Mesec za svetlu temu
    } else {
      themeIcon.className = "bi bi-sun-fill"; // Sunce za tamnu temu
    }
  }

  document
    .getElementById("themeToggle")
    .addEventListener("click", () => toggleThemeAndIcon("theme-icon"));

  document
    .getElementById("themeToggleDesktop")
    .addEventListener("click", () => toggleThemeAndIcon("theme-icon-desktop"));

  document.addEventListener("DOMContentLoaded", () => {
    const savedTheme = sessionStorage.getItem("preferredTheme") || "light";
    document.documentElement.setAttribute("data-bs-theme", savedTheme);

    const updateIcons = () => {
      const themeIconMobile = document.getElementById("theme-icon");
      const themeIconDesktop = document.getElementById("theme-icon-desktop");
      if (savedTheme === "light") {
        themeIconMobile.className = "bi bi-moon-fill";
        themeIconDesktop.className = "bi bi-moon-fill";
      } else {
        themeIconMobile.className = "bi bi-sun-fill";
        themeIconDesktop.className = "bi bi-sun-fill";
      }
    };

    updateIcons();
  });
</script>